name: CI_action

on:
  push:
    branches: [main,test_case_branch]
  pull_request:
    branches: [main,test_case_branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      # UNCOMMENT WHEN TESTS ADDED
      -  name: Run the tests
        run: npm test

      - name: Build
        run: npm run build
